// resources/views/pages/register/page.vue
<template>
    <div class="mw-register-header">
        <h1 class="mw-register-h1">Zaregistrovat se do MW</h1>
    </div>
    <div class="mw-register-container">
        <ValidationAlert :errors="form.errors" />
        <form
            class="form"
            @submit.prevent="submitForm">
            <InputText
                v-model="form.email"
                label="Email"
                type="email"
                name="email"
                required />
            <InputText
                v-model="form.username"
                label="Uživatelské jméno"
                name="username" />
            <InputPassword
                v-model="form.password"
                label="Heslo"
                type="password"
                name="password" />
            <InputPassword
                v-model="form.password_confirmation"
                label="Heslo (Ověření)"
                type="password"
                name="password_confirmation" />
            <SubmitButton
                class="font-medium"
                :processing="form.processing"
                >Zaregistrovat se</SubmitButton
            >
        </form>
    </div>
    <div class="mw-register-container second">
        <h1 class="header">Máte u nás už účet?</h1>
        <p class="description">V tom případě se stačí přihlásit na stránce login a užij si náš projekt MUJIWA.</p>
        <Link
            :href="route('login')"
            class="link"
            >Přihlásit se</Link
        >
    </div>
</template>

<script lang="ts" setup>
const form = useForm<App.Data.Auth.RegisterRequest>('register', {
    username: '',
    email: '',
    password: '',
    password_confirmation: '',
})

const submitForm = () => {
    form.post(route('register'), { preserveScroll: true })
}
</script>

<script lang="ts">
import LayoutAuth from '@/views/layouts/auth/layoutAuth.vue'

export default defineComponent({
    layout: LayoutAuth,
})
</script>

<style lang="css" scoped>
.mw-register-container {
    @apply mt-4 rounded-xl bg-white py-8 px-4 shadow sm:px-10;
}

.mw-register-container.second {
    @apply bg-slate-900 text-slate-50;
}

.mw-register-container .form {
    @apply space-y-6;
}

.mw-register-header {
    @apply mx-auto w-full max-w-md;
}

.mw-register-header .mw-register-h1 {
    @apply text-center text-xl font-medium text-slate-900;
}

.mw-register-container.second .header {
    @apply font-bold leading-7 tracking-tight;
}

.mw-register-container.second .description {
    @apply mt-1 text-sm font-medium leading-5 text-slate-400;
}

.mw-register-container.second .link {
    @apply mt-4 flex items-center justify-center rounded-md bg-white px-4 py-3 font-medium text-slate-900 transition hover:bg-slate-100 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-slate-900;
}
</style>

// resources/js/pages/auth/register/index.jsx
import Auth from "@shared/layouts/auth/Auth";
import Balancer from "react-wrap-balancer";
import {motion} from "framer-motion";
import useRoute from "@hooks/useRoute";
import {Link, useForm} from "@inertiajs/react";
import InputField from "@shared/InputField";
import InputButton from "@shared/InputButton";
import ErrorMessage from "@shared/ErrorMessage";

const RegisterPage = () => {
    return <>
        <motion.div initial={{opacity: 0, x: -50}} animate={{opacity: 1, x: 0}} exit={{opacity: 0, x: 50}} transition={{type: 'spring'}}>
        <div className={'max-w-lg w-full mx-auto mt-6'}>
            <h6 className={'block text-center text-xl sm:text-3xl font-bold tracking-tight text-slate-900'}>
                <Balancer>Vytvořte si svůj účet MW</Balancer>
            </h6>
        </div>
        <div className={'shadow-md rounded-md overflow-hidden grid grid-cols-1 mt-8 mx-auto max-w-lg w-full'}>
            <Form />
        </div>
            <span className={'mt-2 mx-auto block max-w-lg w-full text-center text-sm font-medium text-slate-400'}>Formulář je chráněn Turnstile od společnosti Cloudflare</span>
        </motion.div>
    </>
}

const Form = () => {

    const route = useRoute()

    const form = useForm({'username': '', 'email': '', 'password': '', 'password_confirmation': '', 'cf-turnstile-response': ''})

    const inputHandle = el => {
        const {name, value} = el.target;
        form.setData(name, value);
    }

    const formSubmit = e => {
        e.preventDefault();
        form.post(route('register'));
    }

    return <div className={'bg-white px-6 py-8'}>
        <ErrorMessage errors={form.errors} />
        <form onSubmit={formSubmit} className={'space-y-4'}>
            <InputField
                label={'Uživatelské jméno'}
                name={'username'}
                handler={inputHandle}
                type={'text'}
                value={form.data.username}
            />
            <InputField
                label={'Email'}
                name={'email'}
                handler={inputHandle}
                type={'email'}
                value={form.data.email}
            />
            <InputField
                label={'Heslo'}
                name={'password'}
                handler={inputHandle}
                type={'password'}
                value={form.data.password}
            />
            <InputField
                label={'Heslo (Ověření)'}
                name={'password_confirmation'}
                handler={inputHandle}
                type={'password'}
                value={form.data.password_confirmation}
            />
            <InputButton type={'submit'} loading={form.processing} className={`text-slate-50 ${form.processing ? 'bg-slate-900 hover:bg-slate-800 focus:bg-slate-800' : 'bg-brand hover:bg-blue-600 focus:bg-blue-600'} focus:outline-none focus-within:ring-2 focus-within:ring-offset-1 ${form.processing ? 'focus-within:ring-slate-900 focus-within:ring-offset-white' : 'focus-within:ring-brand focus-within:ring-offset-white'} transition`}>Zaregistrovat se</InputButton>
            <div className={'flex items-center justify-center gap-2'}>
                <span className={'block text-slate-900 font-medium text-sm'}>Už máte u nás účet?</span>
                <Link href={route('login')} className={'text-sm text-brand underline hover:text-blue-600 focus:outline-none focus-within:ring-1 focus-within:ring-brand focus-within:rounded focus-within:ring-offset-2 focus-within:ring-offset-white'}>Přihlásit se</Link>
            </div>
        </form>
    </div>
}

RegisterPage.layout = page => <Auth>{page}</Auth>

export default RegisterPage;
